### ISSUE TITLE
Changing size of splitter on VI that is a member of a class removes the class membership

### ISSUE THREAD

**Issue by HopeHarrison** [HopeHarrison/PaneRelief#1]

**Comment by matrixx567** [comment]
Hy,

I found a solution for this problem:

The `Save VI with XML Heaps.vi` creates a copy of the VI in a temporary folder`. During the save process LabView will remove the linking to the class.

I add an option to overwrite the original VI within the `Save VI with XML Heaps.vi`. Therefore LabView will keep the linked class. 
![Save VI with XML Heaps](https://user-images.githubusercontent.com/4608946/81911623-de61b100-95cd-11ea-9bbb-143ae1ef40d5.png)

In the `Set Splitter Size (Core).vi` I call the `Save VI with XML Heaps.vi` with the overwrite option only if the VI is in a library or class. This will prohibit LabView to disconnect the VI from its class. I also add a cleanup routine to remove the temporary created VI.
![Splitter lvclass_Set Splitter Size (Core)](https://user-images.githubusercontent.com/4608946/81911619-ddc91a80-95cd-11ea-8c66-d20f5be7901a.png)

The only drawback of this change is that the VI can't undo the operation.
I also ask myself if I should save the VI again with the `Save Instruments` method after copying the VI back to remove the XML heap.  I leave this function out because usually I make another changes to the VI and therefore the VI will be saved without the XML heap.

Greets
Martin

PS: You will find the changes in my clone of the project (https://github.com/matrixx567/LabView_PaneRelief). I didn't make a pull request because there are some troubles with the dependencies and LabView versions within my LabView environment.
The two images within this post are VI snippets. Download it to your computer and then insert it to LabView. Then the code should be inserted to LabView.

**Comment by HopeHarrison** [comment]
Wow thanks, great fix!

**Comment by Bas-vE** [comment]
I'm still encountering this problem when trying to set the splitter size to 0px when a vi is part of a class.

I had to move the vi from the class to the root of the project and restart labview to achive the 0px  size

**Comment by Bas-vE** [comment]
Nevermind, it works, forgot my class was readonly
