### ISSUE TITLE
"Set Min Pane Size To Current" feature

### ISSUE THREAD

**Issue by HopeHarrison** [HopeHarrison/PaneRelief#6]
There should be a button under "Min Pane Size" called "Set Min Pane Size To Current" that sets the minimum pane size to whatever size the pane currently is.

**Comment by Monkeymerlot** [comment]
Would something like this work?
Front Panel:
![image](https://user-images.githubusercontent.com/37567672/86812367-f1808280-c04c-11ea-81e4-5dccd242bade.png)

Added an event case. Local is to update the values of the min pane size. And since this is technically an update a message gets sent:
![image](https://user-images.githubusercontent.com/37567672/86812329-e62d5700-c04c-11ea-91f1-cc6647e82db0.png)

And to actually set the minimum size to the current, we would use the content rectangle, get width and height, and set it using the accessor. The size gets returned so we can update the front panel:
![image](https://user-images.githubusercontent.com/37567672/86813108-c185af00-c04d-11ea-9615-3a97341ffd93.png)

**Comment by HopeHarrison** [comment]
Yes I think that will work great, thank you!

**Comment by Monkeymerlot** [comment]
Ok cool. What version of LabVIEW would I need? Or would you prefer to implement the changes yourself?

**Comment by HopeHarrison** [comment]
It's in 2015, feel free to implement it!

**Comment by Monkeymerlot** [comment]
Ok I implemented the changes in a fork: https://github.com/Monkeymerlot/PaneRelief . It only has two commits: One for the class update with the new function, and one updating the actor core. Let me know if there needs any changes!

**Comment by Monkeymerlot** [comment]
I forgot to make a pull request and after doing so I decided to check if the button would actually fit on the subpanel:

![image](https://user-images.githubusercontent.com/37567672/87211497-afbf3880-c2e7-11ea-8ea2-f2e5835fa25e.png)

So I tried bringing it up to try and fit it in without the boxes for the min and max value and the button overlapping but to no avail:
![image](https://user-images.githubusercontent.com/37567672/87211541-f90f8800-c2e7-11ea-9fd6-b5b6428baf3a.png)

I'm obviously not as good as UIs as you are, but I can think of a few options:

1. Bring it up so its basically touching the Min and Max size box(minor overlap):

![image](https://user-images.githubusercontent.com/37567672/87211629-63c0c380-c2e8-11ea-8a50-594e32026560.png)
but this barely fits and makes it look like part of the cluster. Maybe this is ok?

2. Make the text smaller:

![image](https://user-images.githubusercontent.com/37567672/87211693-b4382100-c2e8-11ea-9fb2-ce974e986ef9.png)
(From 15pt Arial to 14pt Arial)
This looks a little off but could work

3. Move everything up to take advantage of the empty space at the top:

![image](https://user-images.githubusercontent.com/37567672/87211850-86071100-c2e9-11ea-823b-35bccfeb69f8.png)
But this would require moving them for all subpanels as they currently line up:
![image](https://user-images.githubusercontent.com/37567672/87211842-75569b00-c2e9-11ea-9216-503dd4546a62.png)


Let me know if you have any ideas or thoughts on this!
Also sorry for any confusion involving the pull request and then cancellation of the pull request in your inbox btw!
